# Generated by Django 5.0.1 on 2024-03-13 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_investigator', models.CharField(max_length=255)),
                ('primary_contact', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('lab_room_number', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255)),
                ('contact_after_hours', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('request_category', models.CharField(max_length=255)),
                ('grant_code', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('plant_species', models.CharField(max_length=255)),
                ('safety_concern', models.BooleanField(default=False)),
                ('current_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('zone_number', models.CharField(max_length=255)),
                ('number_of_tables', models.IntegerField()),
                ('photoperiod', models.IntegerField()),
                ('min_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requirements_clarification', models.TextField()),
                ('applicant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请账号')),
            ],
        ),
    ]
