# Generated by Django 5.0.1 on 2024-03-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
