# Generated by Django 5.0.1 on 2024-03-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrequest',
            name='approved',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'declined')], default=0, verbose_name='approve status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/static/avatars/'),
        ),
    ]
