# Generated by Django 5.0.1 on 2024-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_researchrequest_approved_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/static/avatars/photo-1587822463356-cd0b11a919ae.jpg', null=True, upload_to='users/static/avatars/'),
        ),
    ]
