# Generated by Django 5.0.1 on 2024-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_researchrequest_price_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrequest',
            name='bench',
            field=models.CharField(default='', max_length=255),
        ),
    ]
