# Generated by Django 5.0.1 on 2024-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_researchrequest_bench'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Animal Care'),
        ),
    ]
