# Generated by Django 5.0.1 on 2024-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_researchrequest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supervisor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
