# Generated by Django 5.0.1 on 2024-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='queen',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0, verbose_name='queen'),
        ),
    ]
