# Generated by Django 5.0.1 on 2024-03-29 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_bill_price_billdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetail',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billdetail',
            name='price',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('research_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.researchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detail_number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='users.order')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.price')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillDetail',
        ),
    ]
