# Generated by Django 5.0.1 on 2024-03-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_billdetail_bill_remove_billdetail_price_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchrequest',
            name='price',
        ),
    ]
