# Generated by Django 5.0.1 on 2024-03-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_researchrequest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basic_billing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
