# Generated by Django 5.0.1 on 2024-03-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_order_basic_billing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='external_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
