# Generated by Django 5.0.1 on 2024-03-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_price_external_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='users/static/pdfs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
