# Generated by Django 5.0.1 on 2024-03-31 01:56

import users.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_order_attachment_order_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='review_file',
            field=models.FileField(blank=True, null=True, upload_to='users/static/files/', validators=[users.validate.validate_file_extension]),
        ),
    ]
