# Generated by Django 5.0.1 on 2024-03-08 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=128, unique=True, verbose_name='酒店名')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(verbose_name='酒店房间号')),
                ('refer_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelmodel', to_field='hotel_name')),
            ],
        ),
    ]
