# Generated by Django 5.0.1 on 2024-03-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='used',
            field=models.BooleanField(default=False, verbose_name='酒店是否被预定'),
        ),
    ]
