# Generated by Django 3.2 on 2024-03-10 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('greenhouse', 'Greenhouse Zone'), ('chamber', 'Growth Chamber')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours_light', models.IntegerField()),
                ('hours_dark', models.IntegerField()),
                ('temp_light', models.FloatField()),
                ('temp_dark', models.FloatField()),
                ('humidity_light', models.FloatField()),
                ('humidity_dark', models.FloatField()),
                ('light_level', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.user')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('greenhouse', 'Greenhouse Zone'), ('chamber', 'Growth Chamber')], max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('bookings', models.ManyToManyField(to='booking.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.user'),
        ),
    ]
