# Generated by Django 3.2 on 2024-03-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='facility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.facility'),
            preserve_default=False,
        ),
    ]
